language: go

dist: focal

os:
  - linux

env:
  - GO111MODULE=on

go:
  - 1.15.x
  - 1.16.x
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.1

script:
   - make ci_tests

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
