name: Continues Integration

on:
  push:
    branches:
      - master
      - feature/*
      - bugfix/*
    tags:
      - "*"
  pull_request:
    branches:
      - master
      - feature/*
      - bugfix/*
      - refactor/*
      - chore/*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.22"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Running Tests
        run: make ci_tests

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella

  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.22"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Check for go vulnerabilities
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: WriteGoList
        run: go list -json -deps > go.list

      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.22"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          args: --timeout 5m0s
